
title: My Resume
url: 'http://rasikarampichai.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: rasika  rampichai  ## put your name
title: 'Rasika &amp; 57122420509'  ## your title
location: Ubon , CA


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
